# Generated by Django 4.0.1 on 2022-01-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to='images/')),
                ('Target', models.IntegerField()),
                ('Collected', models.IntegerField()),
                ('Info', models.CharField(max_length=200)),
                ('Date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
