# Generated by Django 4.0.2 on 2022-04-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othercampaign',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='othercampaign',
            name='Dontaion_count',
        ),
    ]
