# Generated by Django 4.0.2 on 2022-04-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_othercampaign_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercampaign',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='othercampaign',
            name='Dontaion_count',
            field=models.IntegerField(default=0),
        ),
    ]
