# Generated by Django 4.0.2 on 2022-04-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_othercampaign_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercampaign',
            name='Sum',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
