# Generated by Django 4.0.1 on 2022-01-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gallery_alter_othercampaign_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='img',
            new_name='Image',
        ),
    ]
