# Generated by Django 4.0.2 on 2022-04-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_othercampaign_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othercampaign',
            name='Sum',
        ),
    ]
