# Generated by Django 4.0.1 on 2022-01-31 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_img_gallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='othercampaign',
            options={'ordering': ['-id']},
        ),
    ]
