# Generated by Django 4.0.2 on 2022-03-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_othercampaign_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercampaign',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
