# Generated by Django 4.0.3 on 2022-03-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_khalti_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Khalti_Payment',
            new_name='Khalti',
        ),
    ]
