# Generated by Django 4.0.3 on 2022-03-20 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_amt_khalti_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercampaign',
            name='totalCollected',
            field=models.IntegerField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
