# Generated by Django 4.0.3 on 2022-03-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_othercampaign_totalcollected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.RemoveField(
            model_name='othercampaign',
            name='totalCollected',
        ),
    ]
