# Generated by Django 4.0.3 on 2022-03-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_campaign_remove_othercampaign_totalcollected'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='desc',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
