# Generated by Django 4.0.3 on 2022-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_gallery_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='desc',
            field=models.CharField(default='Img description', max_length=200),
        ),
    ]
