# Generated by Django 4.0.3 on 2022-03-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_gallery_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='desc',
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
