# Generated by Django 4.0.3 on 2022-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_gallery_desc_gallery_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Khalti',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.AddField(
            model_name='othercampaign',
            name='amount',
            field=models.IntegerField(default=None),
        ),
    ]
