# Generated by Django 4.0.3 on 2022-04-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_khalti_remove_gallery_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othercampaign',
            name='payment_completed',
        ),
        migrations.AlterField(
            model_name='othercampaign',
            name='amount',
            field=models.IntegerField(blank=True),
        ),
    ]
