# Generated by Django 4.0.3 on 2022-04-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_othercampaign_payment_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khalti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='othercampaign',
            name='amount',
        ),
    ]
