# Generated by Django 4.0.3 on 2022-04-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_gallery_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='desc',
        ),
    ]
