# Generated by Django 4.0.3 on 2022-04-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_gallery_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='desc',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
