# Generated by Django 4.0.3 on 2022-04-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_gallery_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
